### ISSUE TITLE
2.13 support

### ISSUE THREAD

**Issue by pshirshov** [djspiewak/parseback#38]
Scala 2.13 is coming, it would be great to see this project available for it.

**Comment by djspiewak** [comment]
I’m blocked on cats, unfortunately. Currently in the process of trying to push that forward as much as I can. I agree with you though.

**Comment by SwiftEngineer** [comment]
Now that cats 2.1.0 is out, I thought I'd try my hand at doing the upgrade. My PR breaks CI pretty bad, but hopefully I'll have a fix for that soon. If all else fails, maybe the PR can at least be used by @djspiewak or another contributor as a starting point? 🤞

**Comment by djspiewak** [comment]
@SwiftEngineer Thanks for your work on this! I couldn't quite figure out how to make mima happier within the parseback build alone; I'm pretty sure it needs some smarter handling of this problem in sbt-spiewak itself. Released as 0.4.0!
